import { Resource, isResource, type Resource as AlchemyResource } from "alchemy";
import * as Cloudflare from "alchemy/Cloudflare";
import * as Provider from "alchemy/Provider";
import * as Config from "effect/Config";
import * as ConfigProvider from "effect/ConfigProvider";
import * as Effect from "effect/Effect";
import * as Redacted from "effect/Redacted";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";

type WranglerVar =
	| string
	| number
	| boolean
	| null
	| readonly WranglerVar[]
	| { readonly [key: string]: WranglerVar };

type WranglerObservability = {
	enabled?: boolean;
	head_sampling_rate?: number;
	logs?: {
		enabled?: boolean;
		head_sampling_rate?: number;
		invocation_logs?: boolean;
		persist?: boolean;
		destinations?: string[];
	};
	traces?: {
		enabled?: boolean;
		head_sampling_rate?: number;
		persist?: boolean;
		destinations?: string[];
	};
};

type WranglerSpec = {
	name?: string;
	main?: string;
	compatibility_date?: string;
	compatibility_flags?: string[];
	workers_dev?: boolean;
	observability?: WranglerObservability;
	limits?: Cloudflare.WorkerLimits;
	placement?: Cloudflare.WorkerPlacement;
	triggers?: {
		crons: string[];
	};
	dev?: {
		port?: number;
	};
	vars?: Record<string, WranglerVar>;
	secrets?: {
		required: string[];
	};
	kv_namespaces?: Array<{
		binding: string;
		id?: string;
		preview_id?: string;
	}>;
	r2_buckets?: Array<{
		binding: string;
		bucket_name?: string;
		preview_bucket_name?: string;
	}>;
	d1_databases?: Array<{
		binding: string;
		database_name: string;
		database_id: string;
		preview_database_id?: string;
		migrations_dir?: string;
		migrations_table?: string;
	}>;
	send_email?: Array<{
		name: string;
		destination_address?: string;
		allowed_destination_addresses?: string[];
		allowed_sender_addresses?: string[];
	}>;
	ratelimits?: Array<{
		name: string;
		namespace_id: string;
		simple: {
			limit: number;
			period: 10 | 60;
		};
	}>;
	version_metadata?: {
		binding: string;
	};
	services?: Array<{
		binding: string;
		service: string;
	}>;
	durable_objects?: {
		bindings: Array<{
			name: string;
			class_name: string;
			script_name?: string;
		}>;
	};
	migrations?: Array<{
		tag: string;
		new_sqlite_classes: string[];
	}>;
};

type WranglerJsoncFile = AlchemyResource<
	"Local.WranglerJsoncFile",
	{
		path: string;
		spec: WranglerSpec;
	},
	{
		path: string;
		contents: string;
	}
>;

const WranglerJsoncFile = Resource<WranglerJsoncFile>("Local.WranglerJsoncFile");

const fileSystemError = (operation: string, path: string, cause: unknown) =>
	new Error(`Failed to ${operation} "${path}".`, { cause });

const isFileNotFound = (error: Error): boolean =>
	("code" in error && error.code === "ENOENT") ||
	(error.cause instanceof Error && isFileNotFound(error.cause));

export const WranglerJsoncFileProvider = () =>
	Provider.succeed(WranglerJsoncFile, {
		list: () => Effect.succeed([]),
		diff: () => Effect.succeed({ action: "update" } as const),
		read: Effect.fn(function* ({ olds }) {
			const filePath = resolve(olds.path);
			const contents = yield* Effect.tryPromise({
				try: () => readFile(filePath, "utf8"),
				catch: (cause) => fileSystemError("read", filePath, cause),
			}).pipe(
				Effect.catch((error) =>
					isFileNotFound(error) ? Effect.succeed(undefined) : Effect.fail(error),
				),
			);

			return contents === undefined
				? undefined
				: {
						path: filePath,
						contents,
					};
		}),
		reconcile: Effect.fn(function* ({ news }) {
			const filePath = resolve(news.path);
			const contents = renderWranglerJsonc(news.spec);

			yield* Effect.tryPromise({
				try: () => mkdir(dirname(filePath), { recursive: true }),
				catch: (cause) =>
					fileSystemError("create the parent directory for", filePath, cause),
			});
			yield* Effect.tryPromise({
				try: () => writeFile(filePath, contents),
				catch: (cause) => fileSystemError("write", filePath, cause),
			});

			return {
				path: filePath,
				contents,
			};
		}),
		delete: Effect.fn(function* ({ output }) {
			yield* Effect.tryPromise({
				try: () => rm(output.path, { force: true }),
				catch: (cause) => fileSystemError("remove", output.path, cause),
			});
		}),
	});

const envProvider = ConfigProvider.fromEnv({
	env: Object.fromEntries(
		Object.entries(process.env).filter(
			(entry): entry is [string, string] => entry[1] !== undefined,
		),
	),
	preserveEmptyStrings: true,
});

const renderWranglerJsonc = (spec: WranglerSpec) =>
	[
		"// Generated by Alchemy from the Worker resource.",
		"// Secret values are not written here. Use `.dev.vars` or `wrangler dev --env-file`.",
		JSON.stringify(spec, null, 2),
		"",
	].join("\n");

const toWranglerObservability = (
	observability: Cloudflare.WorkerObservability | undefined,
): WranglerObservability | undefined =>
	observability
		? {
				enabled: observability.enabled,
				head_sampling_rate: observability.headSamplingRate ?? undefined,
				logs: observability.logs
					? {
							enabled: observability.logs.enabled,
							head_sampling_rate: observability.logs.headSamplingRate ?? undefined,
							invocation_logs: observability.logs.invocationLogs,
							persist: observability.logs.persist,
							destinations: observability.logs.destinations,
						}
					: undefined,
				traces: observability.traces
					? {
							enabled: observability.traces.enabled,
							head_sampling_rate: observability.traces.headSamplingRate ?? undefined,
							persist: observability.traces.persist,
							destinations: observability.traces.destinations,
						}
					: undefined,
			}
		: undefined;

const asRelativeModulePath = (fromFile: string, target: string) => {
	const relativePath = relative(dirname(resolve(fromFile)), resolve(target));
	return relativePath.startsWith(".") ? relativePath : `./${relativePath}`;
};

const getConfigPathSegments = Effect.fn(function* (config: Config.Config<unknown>) {
	let pathSegments: Array<string | number> = [];

	const tracer = ConfigProvider.make((path) => {
		if (pathSegments.length === 0) {
			pathSegments = [...path];
		}

		return Effect.succeed(ConfigProvider.makeValue("1"));
	});

	yield* config.parse(tracer).pipe(Effect.ignore);

	if (pathSegments.length === 0) {
		return yield* Effect.die(
			new Error("Unable to infer the original env key from effect/Config."),
		);
	}

	return pathSegments.map(String);
});

const resolveConfigBinding = Effect.fn(function* (config: Config.Config<unknown>) {
	const segments = yield* getConfigPathSegments(config);
	const value = yield* config.parse(envProvider);

	return {
		name: segments.join("_"),
		value,
	};
});

const resolveLiteralOrConfig = Effect.fn(function* (value: unknown) {
	if (Config.isConfig(value)) {
		const resolved = yield* value.parse(envProvider);
		return Redacted.isRedacted(resolved) ? Redacted.value(resolved) : resolved;
	}

	if (Redacted.isRedacted(value)) {
		return Redacted.value(value);
	}

	return value;
});

const omitEmptyCollections = (spec: WranglerSpec): WranglerSpec => ({
	...spec,
	vars: spec.vars && Object.keys(spec.vars).length > 0 ? spec.vars : undefined,
	secrets: spec.secrets && spec.secrets.required.length > 0 ? spec.secrets : undefined,
	kv_namespaces:
		spec.kv_namespaces && spec.kv_namespaces.length > 0 ? spec.kv_namespaces : undefined,
	r2_buckets: spec.r2_buckets && spec.r2_buckets.length > 0 ? spec.r2_buckets : undefined,
	d1_databases: spec.d1_databases && spec.d1_databases.length > 0 ? spec.d1_databases : undefined,
	send_email: spec.send_email && spec.send_email.length > 0 ? spec.send_email : undefined,
	ratelimits: spec.ratelimits && spec.ratelimits.length > 0 ? spec.ratelimits : undefined,
	services: spec.services && spec.services.length > 0 ? spec.services : undefined,
	durable_objects:
		spec.durable_objects && spec.durable_objects.bindings.length > 0
			? spec.durable_objects
			: undefined,
	migrations: spec.migrations && spec.migrations.length > 0 ? spec.migrations : undefined,
});

// A secret bound by the Worker may also be declared as optional, and Wrangler
// rejects a duplicated name.
const pushSecret = (spec: WranglerSpec, name: string) => {
	if (!spec.secrets?.required.includes(name)) spec.secrets?.required.push(name);
};

const isWranglerVar = (value: unknown): value is WranglerVar =>
	value === null ||
	typeof value === "string" ||
	typeof value === "number" ||
	typeof value === "boolean" ||
	(Array.isArray(value) && value.every(isWranglerVar)) ||
	(typeof value === "object" && value !== null && Object.values(value).every(isWranglerVar));

export const writeWranglerJsoncFromWorker = Effect.fn(function* (
	id: string,
	input: {
		worker: Cloudflare.Worker;
		path: string;
		services?: Array<{ binding: string; service: string }>;
		/**
		 * Secret names to declare even when the Worker has no binding for them,
		 * for credentials that are opt-in per environment. Wrangler only warns
		 * about a missing declared secret, and declaring it is what keeps
		 * `wrangler types` emitting the key on machines that never set it.
		 */
		optionalSecrets?: string[];
	},
) {
	const worker = input.worker;
	const props = worker.Props;

	if (!props.main) {
		return yield* Effect.die(
			new Error("This helper only supports Workers declared with `main`."),
		);
	}

	const spec: any = {
		name: props.name,
		main: asRelativeModulePath(input.path, props.main),
		compatibility_date: props.compatibility?.date,
		compatibility_flags: props.compatibility?.flags,
		workers_dev: props.url,
		observability: toWranglerObservability(props.observability),
		limits: props.limits,
		placement: props.placement,
		triggers: props.crons && props.crons.length > 0 ? { crons: props.crons } : undefined,
		dev:
			props.dev && props.dev.mode !== "external" && props.dev.port
				? { port: props.dev.port }
				: undefined,
		vars: {},
		secrets: {
			required: [],
		},
		kv_namespaces: [],
		r2_buckets: [],
		d1_databases: [],
		send_email: [],
		ratelimits: [],
		services: [],
		durable_objects: {
			bindings: [],
		},
		migrations: [],
	};

	for (const service of input.services ?? []) {
		spec.services.push(service);
	}

	for (const [bindingName, bindingInput] of Object.entries(props.env ?? {})) {
		if (Config.isConfig(bindingInput)) {
			const resolved = yield* resolveConfigBinding(bindingInput);

			if (Redacted.isRedacted(resolved.value)) {
				pushSecret(spec, bindingName);
				continue;
			}

			if (!isWranglerVar(resolved.value)) {
				return yield* Effect.die(
					new Error(`Binding "${bindingName}" resolved to a non-JSON Wrangler var.`),
				);
			}

			spec.vars![bindingName] = resolved.value;
			continue;
		}

		const binding = Effect.isEffect(bindingInput) ? yield* bindingInput : bindingInput;

		if (Redacted.isRedacted(binding)) {
			pushSecret(spec, bindingName);
			continue;
		}

		if (Cloudflare.Email.isSendEmail(binding)) {
			spec.send_email?.push({
				name: bindingName,
				destination_address: binding.destinationAddress,
				allowed_destination_addresses: binding.allowedDestinationAddresses,
				allowed_sender_addresses: binding.allowedSenderAddresses,
			});
			continue;
		}

		if (Cloudflare.isRateLimit(binding)) {
			spec.ratelimits?.push({
				name: bindingName,
				namespace_id: binding.namespaceId,
				simple: binding.simple,
			});
			continue;
		}

		if (Cloudflare.isVersionMetadata(binding)) {
			if (spec.version_metadata) {
				return yield* Effect.die(
					new Error("Wrangler only supports a single `version_metadata` binding."),
				);
			}

			spec.version_metadata = {
				binding: bindingName,
			};
			continue;
		}

		if (Cloudflare.isDurableObjectLike(binding)) {
			const className = binding.className ?? binding.name;
			const scriptName = binding.scriptName
				? yield* resolveLiteralOrConfig(binding.scriptName)
				: undefined;
			spec.durable_objects?.bindings.push({
				name: bindingName,
				class_name: className,
				...(typeof scriptName === "string" ? { script_name: scriptName } : {}),
			});
			if (scriptName === undefined) {
				spec.migrations?.push({
					tag: `v1-${binding.name}`,
					new_sqlite_classes: [className],
				});
			}
			continue;
		}

		if (isResource(binding)) {
			switch (binding.Type) {
				case "Cloudflare.D1Database": {
					const database = binding as Cloudflare.D1.Database;

					spec.d1_databases?.push({
						binding: bindingName,
						database_name: database.databaseName,
						database_id: database.databaseId,
						preview_database_id: database.databaseId,
						migrations_dir: database.Props.migrationsDir
							? asRelativeModulePath(input.path, database.Props.migrationsDir)
							: undefined,
						migrations_table: database.Props.migrationsTable,
					});
					continue;
				}
				case "Cloudflare.KV.Namespace": {
					const namespace = binding as Cloudflare.KV.Namespace;

					spec.kv_namespaces?.push({
						binding: bindingName,
						id: namespace.namespaceId,
						preview_id: namespace.namespaceId,
					});
					continue;
				}
				case "Cloudflare.R2.Bucket": {
					const bucket = binding as Cloudflare.R2.Bucket;

					spec.r2_buckets?.push({
						binding: bindingName,
						bucket_name: bucket.bucketName,
						preview_bucket_name: bucket.bucketName,
					});
					continue;
				}
				case "Cloudflare.Worker": {
					const service = binding as Cloudflare.Worker;

					spec.services?.push({
						binding: bindingName,
						service: service.workerName,
					});
					continue;
				}
			}
		}

		if (!isWranglerVar(binding)) {
			return yield* Effect.die(
				new Error(
					`Unsupported Worker binding "${bindingName}" while generating wrangler.jsonc.`,
				),
			);
		}

		spec.vars![bindingName] = binding;
	}

	for (const secretName of input.optionalSecrets ?? []) {
		pushSecret(spec, secretName);
	}

	return yield* WranglerJsoncFile(id, {
		path: input.path,
		spec: omitEmptyCollections(spec),
	});
});
