/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppCardsRouteImport } from './routes/_app/cards'
import { Route as AppChatRouteRouteImport } from './routes/_app/chat/route'
import { Route as AppInvestmentsRouteImport } from './routes/_app/investments'
import { Route as AppOpenFinanceRouteImport } from './routes/_app/open-finance'
import { Route as AppOverviewRouteImport } from './routes/_app/overview'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AppChatIndexRouteImport } from './routes/_app/chat/index'
import { Route as AppChatSessionIdRouteImport } from './routes/_app/chat/$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCardsRoute = AppCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChatRouteRoute = AppChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInvestmentsRoute = AppInvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOpenFinanceRoute = AppOpenFinanceRouteImport.update({
  id: '/open-finance',
  path: '/open-finance',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChatRouteRoute,
} as any)
const AppChatSessionIdRoute = AppChatSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => AppChatRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof AppChatRouteRouteWithChildren
  '/cards': typeof AppCardsRoute
  '/investments': typeof AppInvestmentsRoute
  '/open-finance': typeof AppOpenFinanceRoute
  '/overview': typeof AppOverviewRoute
  '/transactions': typeof AppTransactionsRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/chat/$sessionId': typeof AppChatSessionIdRoute
  '/chat/': typeof AppChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cards': typeof AppCardsRoute
  '/investments': typeof AppInvestmentsRoute
  '/open-finance': typeof AppOpenFinanceRoute
  '/overview': typeof AppOverviewRoute
  '/transactions': typeof AppTransactionsRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/chat/$sessionId': typeof AppChatSessionIdRoute
  '/chat': typeof AppChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/chat': typeof AppChatRouteRouteWithChildren
  '/_app/cards': typeof AppCardsRoute
  '/_app/investments': typeof AppInvestmentsRoute
  '/_app/open-finance': typeof AppOpenFinanceRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_app/chat/$sessionId': typeof AppChatSessionIdRoute
  '/_app/chat/': typeof AppChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/cards'
    | '/investments'
    | '/open-finance'
    | '/overview'
    | '/transactions'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/chat/$sessionId'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cards'
    | '/investments'
    | '/open-finance'
    | '/overview'
    | '/transactions'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/chat/$sessionId'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/chat'
    | '/_app/cards'
    | '/_app/investments'
    | '/_app/open-finance'
    | '/_app/overview'
    | '/_app/transactions'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_app/chat/$sessionId'
    | '/_app/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/cards': {
      id: '/_app/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof AppCardsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/investments': {
      id: '/_app/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof AppInvestmentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/open-finance': {
      id: '/_app/open-finance'
      path: '/open-finance'
      fullPath: '/open-finance'
      preLoaderRoute: typeof AppOpenFinanceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/chat/': {
      id: '/_app/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppChatRouteRoute
    }
    '/_app/chat/$sessionId': {
      id: '/_app/chat/$sessionId'
      path: '/$sessionId'
      fullPath: '/chat/$sessionId'
      preLoaderRoute: typeof AppChatSessionIdRouteImport
      parentRoute: typeof AppChatRouteRoute
    }
  }
}

interface AppChatRouteRouteChildren {
  AppChatSessionIdRoute: typeof AppChatSessionIdRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
}

const AppChatRouteRouteChildren: AppChatRouteRouteChildren = {
  AppChatSessionIdRoute: AppChatSessionIdRoute,
  AppChatIndexRoute: AppChatIndexRoute,
}

const AppChatRouteRouteWithChildren = AppChatRouteRoute._addFileChildren(
  AppChatRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppChatRouteRoute: typeof AppChatRouteRouteWithChildren
  AppCardsRoute: typeof AppCardsRoute
  AppInvestmentsRoute: typeof AppInvestmentsRoute
  AppOpenFinanceRoute: typeof AppOpenFinanceRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppChatRouteRoute: AppChatRouteRouteWithChildren,
  AppCardsRoute: AppCardsRoute,
  AppInvestmentsRoute: AppInvestmentsRoute,
  AppOpenFinanceRoute: AppOpenFinanceRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppTransactionsRoute: AppTransactionsRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
