import z from "zod";

export const uuidV7Field = z.uuidv7().meta({
	description: "Identifier generated by this API. Time-ordered UUID v7.",
	example: "019318f2-7c41-7a3b-8f2e-1abdcf496130",
	externalDocs: {
		description: "Official UUID standard specification (RFC 9562)",
		url: "https://www.rfc-editor.org/rfc/rfc9562",
	},
	format: "uuid",
});

/** Any UUID we do not mint ourselves, so its version is not ours to require. */
export const uuidField = z.uuid().meta({
	description: "Unique UUID that identifies the entity. Follows the RFC 4122 standard format.",
	example: "550e8400-e29b-41d4-a716-446655440000",
	externalDocs: {
		description: "Official UUID standard specification (RFC 4122)",
		url: "https://www.rfc-editor.org/rfc/rfc4122",
	},
	format: "uuid",
});
